### ISSUE TITLE
Changes in MMD tools causes an error while fixing model.

### ISSUE THREAD

**Issue by Yusarina** [Yusarina/Cats-Blender-Plugin-Unofficial-#9]
Though it does not seem like this error effects anything it can be annoying.

Python: Traceback (most recent call last):
  File "PATHTOFILE", line 1250, in execute
    bpy.ops.mmd_tools.set_shadeless_glsl_shading()
  File "PATHTOFILE", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.mmd_tools.set_shadeless_glsl_shading" error, could not be found

This is probs going to be fixed in 0.3.1.

**Comment by Yusarina** [comment]
This is fixed and will be released in version 0.3.1
